### ISSUE TITLE
ipad iOS keyboard QWERTY layout

### ISSUE THREAD

**Issue by MadDeveloper** [hodgef/simple-keyboard-layouts#23]
Sorry about doing this in a issue, but I don't see where I can do it elsewhere 😅
I'm creating an issue in this project because of its name, but the files inside it don't indicate where I can put the following layout code. So I post it here, and I let you tell me where it can goes:

```javascript
// ipad iOS QWERTY layout
const layout = {
  default: [
    'q w e r t y u i o p {bksp}',
    'a s d f g h j k l {enter}',
    '{shift} z x c v b n m , . {shift}',
    '{alt} {smileys} {space} {altright} {downkeyboard}'
  ],
  shift: [
    'Q W E R T Y U I O P {bksp}',
    'A S D F G H J K L {enter}',
    '{shiftactivated} Z X C V B N M , . {shiftactivated}',
    '{alt} {smileys} {space} {altright} {downkeyboard}'
  ],
  alt: [
    '1 2 3 4 5 6 7 8 9 0 {bksp}',
    `@ # $ & * ( ) ' " {enter}`,
    '{shift} % - + = / ; : ! ? {shift}',
    '{default} {smileys} {space} {back} {downkeyboard}'
  ],
  smileys: [
    '😀 😊 😅 😂 🙂 😉 😍 😛 😠 😎 {bksp}',
    `😏 😬 😭 😓 😱 😪 😬 😴 😯 {enter}`,
    '😐 😇 🤣 😘 😚 😆 😡 😥 😓 🙄 {shift}',
    '{default} {smileys} {space} {altright} {downkeyboard}'
  ]
}
```

```scss
@import '../../assets/styles/variables';

/**
 * hg-theme-default theme
 */
.simple-keyboard {
  width: 750px;
  margin: auto;

  .hg-button {
    display: inline-block;
    flex-grow: 1;
    cursor: pointer;
  }

  .hg-row {
    display: flex;

    &:not(:last-child) {
      margin-bottom: $keyboard-margins;
    }

    .hg-button:not(:last-child) {
      margin-right: $keyboard-margins;
    }

    &:nth-child(2) {
      margin-left: 18px;
    }
  }

  &.hg-theme-default {
    background-color: rgba(0, 0, 0, 0.1);
    padding: 5px;
    border-radius: 5px;

    &.hg-layout-custom {
      background-color: $keyboard-background-color;
      padding: 5px;
    }

    .hg-button {
      border-radius: 5px;
      box-sizing: border-box;
      padding: 0;
      background: white;
      border-bottom: 1px solid #b5b5b5;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: none;
      font-weight: 400;
      font-size: 20px;
      max-width: 60px;
      min-width: 60px;
      height: 60px;
      min-height: 60px;

      &:active,
      &:focus {
        background: #e4e4e4;
      }

      &.hg-functionBtn {
        background-color: $keyboard-button-action-color;
      }

      &.hg-button-space,
      &.hg-button-shift,
      &.hg-button-shiftactivated {
        background-color: #ffffff;
      }
    }

    .hg-button-space {
      max-width: 448px;
      min-width: 448px;
    }

    .hg-button-enter {
      max-width: 110px;
      min-width: 110px;
    }

    .hg-button-altright,
    .hg-button-back {
      min-width: 80px;
      max-width: 80px;
    }
  }
}
```
All sizes are fixed in order to have a better design, but can be readapted following the needs.

And the key press logic:
```js
const isFunctionButton = names => button => [...names].includes(button)
const isShiftButton = isFunctionButton(['{shift}', '{shiftactivated}'])
const isAltButton = isFunctionButton(['{alt}', '{altright}'])
const isSmileysButton = isFunctionButton(['{smileys}'])
const isDefaultButton = isFunctionButton(['{default}'])
```

Here is what it looks:
![iPad iOS QWERTY layout](https://image.ibb.co/eiQp9f/Capture-d-e-cran-2018-11-16-a-12-33-18.png)

Is there a place where all keyboards are organised by layout or by language? For example: where I can find the layout iPad iOS QWERTY or AZERTY? Idem for iOS devices, Android, etc.
